// analysis-admin/src/views/NotFound.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-50 p-4">
    <div class="max-w-2xl w-full text-center space-y-12">
      <!-- 404 Text with Animation -->
      <div class="relative">
        <!-- Background Numbers with Animation -->
        <div class="absolute inset-0 flex items-center justify-center opacity-5">
          <div class="text-[250px] font-bold tracking-widest text-gray-900 animate-pulse">
            404
          </div>
        </div>

        <!-- Main Content -->
        <div class="relative z-10 py-16">
          <!-- Simple 404 Illustration -->
          <div class="flex justify-center mb-8">
            <div class="w-32 h-32 rounded-full bg-indigo-100 flex items-center justify-center">
              <span class="text-6xl text-indigo-600">!</span>
            </div>
          </div>

          <!-- Error Message -->
          <h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Page Not Found
          </h1>
          <p class="text-lg text-gray-600 mb-8 max-w-md mx-auto">
            The page you're looking for doesn't exist or has been moved.
          </p>

          <!-- Action Buttons -->
          <div class="flex flex-col sm:flex-row justify-center gap-4">
            <router-link to="/"
              class="inline-flex items-center px-6 py-3 rounded-lg bg-indigo-600 text-white font-medium hover:bg-indigo-700 transition-all duration-200 transform hover:scale-105">
              <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
              </svg>
              Return Home
            </router-link>
            <button @click="goBack"
              class="inline-flex items-center px-6 py-3 rounded-lg border-2 border-indigo-600 text-indigo-600 font-medium hover:bg-indigo-50 transition-all duration-200 transform hover:scale-105">
              <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 17l-5-5m0 0l5-5m-5 5h12" />
              </svg>
              Go Back
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'NotFound',
  methods: {
    goBack() {
      this.$router.go(-1)
    }
  }
}
</script>

<style scoped>
/* Gradient Animation */
.bg-gradient-to-br {
  background-size: 400% 400%;
  animation: gradient 15s ease infinite;
}

@keyframes gradient {
  0% {
    background-position: 0% 50%;
  }

  50% {
    background-position: 100% 50%;
  }

  100% {
    background-position: 0% 50%;
  }
}

/* Scale animation for buttons */
.transform {
  transition: transform 0.2s;
}

.hover\:scale-105:hover {
  transform: scale(1.05);
}
</style>

// algo/app/not-found.tsx
import Footer from "@/components/sections/Footer";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "404 - Page Not Found",
  description: "The page you are looking for could not be found.",
};

export default function NotFoundPage() {
  return (
    <main className="min-h-screen bg-white">
      {/* Hero Section */}
      <div className="relative bg-[#F6F0E4] py-20 overflow-hidden">
        {/* Background Decorative Elements */}
        <div className="absolute left-0 top-1/3 -translate-y-1/2 z-10">
          <div className="relative">
            <Image
              src="/images/hand.png"
              alt="Hand with Rocket"
              width={300}
              height={200}
              className="w-auto h-auto"
            />
          </div>
        </div>

        <div className="absolute right-20 top-1/2 -translate-y-1/2 z-10">
          <Image
            src="/images/message.png"
            alt="Chat Bubble"
            width={80}
            height={80}
            className="w-auto h-auto"
          />
        </div>

        {/* Content */}
        <div className="container mx-auto px-4 relative z-20">
          <div className="text-center max-w-2xl mx-auto">
            <h1 className="text-4xl font-bold text-[#0B1B2B] mb-4">
              404 Error
            </h1>
            <div className="flex items-center justify-center gap-2 text-gray-600">
              <span>Home</span>
              <span>-</span>
              <span>Pages</span>
              <span>-</span>
              <span>404 Error</span>
            </div>
          </div>
        </div>

        {/* Decorative Elements */}
        <div className="absolute top-0 left-1/4 z-10">
          <Image
            src="/images/decorative.png"
            alt="Decorative Element"
            width={100}
            height={100}
            className="w-auto h-auto opacity-30"
          />
        </div>
      </div>

      {/* 404 Content Section */}
      <div className="container mx-auto px-4 relative z-20">
        <section className="py-16">
          <div className="container mx-auto px-4">
            <div className="max-w-3xl mx-auto text-center">
              {/* 404 Image */}
              <div className="relative w-full h-[300px] mb-12">
                <Image
                  src="/images/404.png"
                  alt="404 Error"
                  fill
                  className="object-contain"
                  priority
                />
              </div>

              {/* Content */}
              <h2 className="text-2xl font-semibold text-[#0B1B2B] mb-4">
                Oops!..Something Went Wrong
              </h2>
              <p className="text-gray-600 mb-12">
                Don&apos;t Worry Our Team is here to help
              </p>

              {/* Support Options */}
              <div className="flex flex-wrap justify-center gap-8 mb-12">
                <div className="flex items-center gap-2">
                  <Image
                    src="/images/404(1).png"
                    alt="Q&A"
                    width={24}
                    height={24}
                  />
                  <span className="text-gray-600">Questions & Answers</span>
                </div>
                <div className="flex items-center gap-2">
                  <Image
                    src="/images/404(2).png"
                    alt="Community"
                    width={24}
                    height={24}
                  />
                  <span className="text-gray-600">Community Forum</span>
                </div>
                <div className="flex items-center gap-2">
                  <Image
                    src="/images/404(3).png"
                    alt="Support"
                    width={24}
                    height={24}
                  />
                  <span className="text-gray-600">Send Support Request</span>
                </div>
              </div>

              {/* Back Home Button */}
              <Link
                href="/"
                className="inline-flex items-center justify-center gap-2 bg-[#0066FF] text-white px-8 py-3 rounded-md hover:bg-blue-700 transition-colors"
              >
                Back Home
              </Link>
            </div>
          </div>
        </section>
      </div>
      <Footer />
    </main>
  );
}
