// algo/app/contact/page.tsx
import Image from "next/image";
import Footer from "@/components/sections/Footer";

export default function ContactPage() {
  return (
    <main className="min-h-screen bg-white overflow-x-hidden">
      {/* Hero Section */}
      <div className="relative bg-[#F6F0E4] py-20 ">
        {/* Background Decorative Elements */}
        <div className="absolute left-0 top-1/3 -translate-y-1/2 z-10">
          <Image
            src="/images/hand.png"
            alt="Hand with Rocket"
            width={300}
            height={200}
            className="w-auto h-auto"
          />
        </div>

        <div className="absolute right-20 top-1/2 -translate-y-1/2 z-10">
          <Image
            src="/images/message.png"
            alt="Chat Bubble"
            width={80}
            height={80}
            className="w-auto h-auto"
          />
        </div>

        {/* Content */}
        <div className="container mx-auto px-4 relative z-20">
          <div className="text-center max-w-2xl mx-auto">
            <h1 className="text-4xl font-bold text-[#0B1B2B] mb-4">
              Contact Us
            </h1>
            <div className="flex items-center justify-center gap-2 text-gray-600">
              <span>Home</span>
              <span>-</span>
              <span>Contact Us</span>
            </div>
          </div>
        </div>

        {/* Decorative Elements */}
        <div className="absolute top-0 left-1/4 z-10">
          <Image
            src="/images/decorative.png"
            alt="Decorative Element"
            width={100}
            height={100}
            className="w-auto h-auto opacity-30"
          />
        </div>
      </div>

      {/* World Map Section */}
      <section className="pt-10 pb-3">
        <div className="container mx-auto px-0">
        <div className="relative">
  {/* World Map Background */}
  <div className="flex justify-center">
    <Image
      src="/images/Layer_1.png"
      alt="World Map"
      width={900}
      height={100}
      className="opacity-90"
    />
  </div>
  <div className="absolute top-[32%] left-[45%]">
    <div className="relative">
      <div className="w-2 h-2 bg-gray-500 rounded-full relative z-10"></div>
    </div>
  </div>
  <div className="absolute top-[52%] left-[15%]">
    <div className="relative">
      <div className="w-2 h-2 bg-gray-500 rounded-full relative z-10"></div>
    </div>
  </div>
  {/* Singapore Office */}
  <div className="absolute top-[52%] left-[75%]">
    <div className="relative">
      <div className="w-1 h-1 bg-[#0561FC] rounded-full animate-ping absolute opacity-75"></div>
      <div className="w-2 h-2 bg-[#0561FC] rounded-full relative z-10"></div>
      <div className="absolute top-full left-1/2 -translate-x-1/2 mt-2 bg-[#0561FC] text-white px-4 py-2 rounded-lg text-xs whitespace-nowrap shadow-lg">
        <p>IT Services & Software Solutions</p>
        <p>45, Singapore</p>
        <p>Ph: +65 123 456 789</p>
      </div>
    </div>
  </div>
</div>

        </div>
      </section>

      {/* Contact Options */}
      <section className="pb-16 pt-0 bg-white ">
  <div className="container mx-auto px-4">
    <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
      {/* Chat For Sales */}
      <div className="bg-white p-6 rounded-xl text-left shadow-2xl transition-all group hover:bg-[#0561FC] hover:text-white">
        <div className="w-12 h-12 rounded-full flex items-center justify-center mb-3">
          <Image
            src="/images/sales.png"
            alt="Chat Sales Icon"
            width={24}
            height={24}
            className="text-[#0561FC] group-hover:fill-white transition-all"
          />
        </div>
        <h3 className="text-[#0B1B2B] font-semibold text-base mb-2 group-hover:text-white transition-all">
          Chat For Sales
        </h3>
        <p className="text-gray-500 text-sm mb-4 group-hover:text-white transition-all">
          Contrary To Popular Belief, Lorem
        </p>
        <button className="text-white text-sm font-medium bg-[#0561FC] px-5 py-2 rounded-full group-hover:bg-white group-hover:text-gray-800 transition-all">
          Sales@Example.Com →
        </button>
      </div>

      {/* Chat For Support */}
      <div className="bg-white p-6 rounded-xl text-left shadow-2xl transition-all group hover:bg-[#0561FC] hover:text-white">
        <div className="w-12 h-12 rounded-full flex items-center justify-center mb-3">
          <Image
            src="/images/chat.png"
            alt="Chat Support Icon"
            width={24}
            height={24}
            className="text-[#0561FC]"
          />
        </div>
        <h3 className="text-[#0B1B2B] font-semibold text-base mb-2 group-hover:text-white transition-all">
          Chat For Support
        </h3>
        <p className="text-gray-500 text-sm mb-4 group-hover:text-white transition-all">
          Contrary To Popular Belief, Lorem
        </p>
        <button className="text-white text-sm font-medium bg-[#0561FC] px-5 py-2 rounded-full group-hover:bg-white group-hover:text-gray-800 transition-all">
          Get In Touch →
        </button>
      </div>

      {/* Visit Our Site */}
      <div className="bg-white p-6 rounded-xl text-left shadow-2xl transition-all group hover:bg-[#0561FC] hover:text-white">
        <div className="w-12 h-12 bg-white/10 rounded-full flex items-center justify-center mb-3">
          <Image
            src="/images/site.png"
            alt="Visit Site Icon"
            width={24}
            height={24}
            className="text-black bg-black rounded-full"
          />
        </div>
        <h3 className="text-[#0B1B2B] font-semibold text-base mb-2 group-hover:text-white transition-all">
          Visit Our Site
        </h3>
        <p className="text-gray-500 text-sm mb-4 group-hover:text-white transition-all">
          Contrary To Popular Belief, Lorem
        </p>
        <button className="text-white text-sm font-medium bg-[#0561FC] px-5 py-2 rounded-full group-hover:bg-white group-hover:text-gray-800 transition-all">
          www.itservices.com →
        </button>
      </div>

      {/* Contact Us */}
      <div className="bg-white p-6 rounded-xl text-left shadow-2xl transition-all group hover:bg-[#0561FC] hover:text-white">
        <div className="w-12 h-12 rounded-full flex items-center justify-center mb-3">
          <Image
            src="/images/contact.png"
            alt="Contact Us Icon"
            width={24}
            height={24}
            className="text-[#0561FC]"
          />
        </div>
        <h3 className="text-[#0B1B2B] font-semibold text-base mb-2 group-hover:text-white transition-all">
          Contact Us
        </h3>
        <p className="text-gray-500 text-sm mb-4 group-hover:text-white transition-all">
          Contrary To Popular Belief, Lorem
        </p>
        <button className="text-white text-sm font-medium bg-[#0561FC] px-5 py-2 rounded-full group-hover:bg-white group-hover:text-gray-800 transition-all">
          +81.000.2323.2 →
        </button>
      </div>
    </div>
  </div>
</section>


      {/* Contact Form Section */}
      <section className="py-16 bg-[#E0EFFF]">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-40">
            {/* Left Side - Contact Info */}
            <div>
              <p className="text-sm text-gray-500 border border-gray-400 font-medium mb-4 inline-block px-3 py-1 rounded-full">
                Contact Address
              </p>

              <h2 className="text-4xl font-bold text-[#0B1B2B] leading-tight mb-6">
                We&apos;re The Future Of{" "}
                <span className="text-[#0561FC]">IT Industry</span>,
                <br />
                Further Contact Us
              </h2>
              <p className="text-gray-500 text-sm leading-relaxed mb-12">
                Lorem Ipsum Is Simply Dummy Text Of The Printing And Typesetting
                Industry. Lorem Ipsum Has Been The Industry&apos;s Standard
                Dummy
              </p>

              {/* Contact Details */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-10 relative">
                {/* Address */}
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0">
                    <Image
                      src="/images/pin.png"
                      alt="Location"
                      width={20}
                      height={20}
                      className="opacity-60"
                    />
                  </div>
                  <div>
                    <h4 className="text-base font-medium text-[#0B1B2B] mb-2">
                      Address
                    </h4>
                    <p className="text-sm text-gray-500 leading-relaxed">
                    C-104 Sector 65 Noida
                    </p>
                  </div>
                </div>

                {/* Phone Number */}
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0">
                    <Image
                      src="/images/transport.png"
                      alt="Phone"
                      width={20}
                      height={20}
                      className="opacity-60"
                    />
                  </div>
                  <div>
                    <h4 className="text-base font-medium text-[#0B1B2B] mb-2">
                      Phone Number
                    </h4>
                    <p className="text-sm text-gray-500 leading-relaxed">
                    +91 8743045170
                    </p>
                  </div>
                </div>

                {/* Email Id */}
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0">
                    <Image
                      src="/images/email.png"
                      alt="Email"
                      width={20}
                      height={20}
                      className="opacity-60"
                    />
                  </div>
                  <div>
                    <h4 className="text-base font-medium text-[#0B1B2B] mb-2">
                      Email Id
                    </h4>
                    <p className="text-sm text-gray-500 leading-relaxed">
                     hii@algofolks.com
                    </p>
                  </div>
                </div>

                {/* Opening Hours */}
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0">
                    <Image
                      src="/images/clock.png"
                      alt="Clock"
                      width={20}
                      height={20}
                      className="opacity-60"
                    />
                  </div>
                  <div>
                    <h4 className="text-base font-medium text-[#0B1B2B] mb-2">
                      Opening Hours
                    </h4>
                    <p className="text-sm text-gray-500 leading-relaxed">
                      Mon - Sat : M/g (09.00am To
                      <br />
                      09.00pm, Sun - Holiday
                    </p>
                  </div>
                </div>

                {/* Divider Lines */}
                <div className="absolute left-1/2 top-0 bottom-0 w-px bg-gray-300 hidden md:block"></div>
<div className="absolute left-0 right-0 top-[45%] h-px bg-gray-300 hidden md:block"></div>

              </div>
            </div>

            {/* Right Side - Contact Form */}
            <div className="bg-[#0561FC] rounded-3xl p-10 ">
              <h3 className="text-2xl font-bold text-white mb-2">Get Quotes</h3>
              <p className="text-white/80 text-sm mb-8">
                The Point Of Using Lorem Ipsum Is That It Has More-Or-Less
                Normal
              </p>

              <form className="space-y-6">
                {/* Full Name */}
                <div className="relative">
                  <input
                    type="text"
                    placeholder="Full Name"
                    className="w-full bg-transparent text-white border-b border-white/20 pb-3 focus:outline-none focus:border-white text-sm placeholder:text-white/60"
                  />
                </div>

                {/* Email Id */}
                <div className="relative">
                  <input
                    type="email"
                    placeholder="Email Id"
                    className="w-full bg-transparent text-white border-b border-white/20 pb-3 focus:outline-none focus:border-white text-sm placeholder:text-white/60"
                  />
                </div>

               

                {/* Message */}
                <div className="relative">
                  <textarea
                    placeholder="Message"
                    rows={4}
                    className="w-full bg-transparent text-white border-b border-white/20 pb-3 focus:outline-none focus:border-white text-sm placeholder:text-white/60 resize-none"
                  ></textarea>
                </div>

                {/* Submit Button */}
                <button className="flex items-center justify-center gap-2 text-white border border-white px-8 py-3 rounded-full text-sm font-medium hover:bg-white/90 hover:text-blue-600 transition-colors">
                  Submit Now <span className="ml-1">→</span>
                </button>
              </form>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}

// src/components/Contact.vue
<template>
    <section id="contact" class="bg-[#080B16] relative overflow-hidden py-20">
        <!-- Background Effects -->
        <div class="absolute inset-0 bg-gradient-radial from-[#1F2B64]/20 via-[#080B16] to-[#080B16]"></div>

        <!-- Main Content -->
        <div class="mx-4 sm:mx-6 lg:mx-[180px] relative z-10">
            <!-- Contact Card -->
            <div class="bg-white rounded-[32px] p-6 sm:p-8 lg:p-12">
                <h2 class="text-[#080B16] text-3xl sm:text-4xl font-bold text-center mb-6 sm:mb-10">
                    LET'S HAVE A CHAT
                </h2>

                <!-- Contact Form -->
                <form @submit.prevent="handleSubmit" class="space-y-4 sm:space-y-6">
                    <!-- Name Input -->
                    <div>
                        <input type="text" placeholder="YOUR NAME"
                            class="w-full bg-[#F5F5F5] rounded-xl sm:rounded-2xl px-4 sm:px-6 py-3 sm:py-4 text-[#080B16] placeholder-[#080B16]/60 focus:outline-none text-sm sm:text-base" />
                    </div>

                    <!-- Email Input -->
                    <div>
                        <input type="email" placeholder="EMAIL ADDRESS"
                            class="w-full bg-[#F5F5F5] rounded-xl sm:rounded-2xl px-4 sm:px-6 py-3 sm:py-4 text-[#080B16] placeholder-[#080B16]/60 focus:outline-none text-sm sm:text-base" />
                    </div>

                    <!-- Message Input -->
                    <div>
                        <textarea placeholder="CHAT HERE" rows="4"
                            class="w-full bg-[#F5F5F5] rounded-xl sm:rounded-2xl px-4 sm:px-6 py-3 sm:py-4 text-[#080B16] placeholder-[#080B16]/60 focus:outline-none resize-none text-sm sm:text-base"></textarea>
                    </div>

                    <!-- Submit Button -->
                    <button type="submit"
                        class="w-full bg-[#CDFF6B] hover:bg-[#CDFF6B]/90 text-[#080B16] py-3 sm:py-4 rounded-full text-sm sm:text-base font-semibold transition-colors">
                        SUBMIT HERE
                    </button>
                </form>

                <!-- Divider -->
                <div class="flex items-center my-8 sm:my-12">
                    <div class="flex-1 border-t-2 border-[#080B16]/10"></div>
                    <span class="px-4 text-[#080B16] text-sm sm:text-base font-semibold">OR</span>
                    <div class="flex-1 border-t-2 border-[#080B16]/10"></div>
                </div>

                <!-- Contact Information -->
                <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">
                    <!-- Email -->
                    <div class="flex items-center space-x-4 sm:space-x-6">
                        <div
                            class="w-[45px] h-[45px] sm:w-[50px] sm:h-[50px] bg-[#080B16] rounded-full flex items-center justify-center shadow-lg">
                            <i class="fas fa-envelope text-white text-xl sm:text-2xl"></i>
                        </div>
                        <div class="text-left">
                            <h3 class="text-[#080B16] font-semibold mb-1 text-sm sm:text-base">Email</h3>
                            <a href="mailto:vkgupta.dev@gmail.com"
                                class="text-gray-600 hover:text-[#CDFF6B] transition-colors text-sm sm:text-base break-all">
                                vkgupta.dev@gmail.com
                            </a>
                        </div>
                    </div>

                    <!-- Phone -->
                    <div class="flex items-center space-x-4 sm:space-x-6">
                        <div
                            class="w-[45px] h-[45px] sm:w-[50px] sm:h-[50px] bg-[#080B16] rounded-full flex items-center justify-center shadow-lg">
                            <i class="fas fa-phone text-white text-xl sm:text-2xl"></i>
                        </div>
                        <div class="text-left">
                            <h3 class="text-[#080B16] font-semibold mb-1 text-sm sm:text-base">Phone</h3>
                            <a href="tel:+918743045170"
                                class="text-gray-600 hover:text-[#CDFF6B] transition-colors text-sm sm:text-base">
                                +91-8743045170
                            </a>
                        </div>
                    </div>

                    <!-- Address -->
                    <div class="flex items-center space-x-4 sm:space-x-6">
                        <div
                            class="w-[45px] h-[45px] sm:w-[50px] sm:h-[50px] bg-[#080B16] rounded-full flex items-center justify-center shadow-lg">
                            <i class="fas fa-home text-white text-xl sm:text-2xl"></i>
                        </div>
                        <div class="text-left">
                            <h3 class="text-[#080B16] font-semibold mb-1 text-sm sm:text-base">Address</h3>
                            <p class="text-gray-600 text-sm sm:text-base">
                                C 104, Sector 65<br />
                                Noida, 201301<br />
                                India
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script>
export default {
    name: 'Contact-component',
    methods: {
        handleSubmit(e) {
            e.preventDefault();
            // Handle form submission logic here
            console.log('Form submitted');
        }
    }
}
</script>

<style scoped>
.bg-gradient-radial {
    background-image: radial-gradient(circle at 50% 0%, var(--tw-gradient-from) 0%, var(--tw-gradient-via) 40%, var(--tw-gradient-to) 100%);
}
</style>
